export const FETCH_AIRPORTS = "FETCH_AIRPORTS";
export const FETCH_DEPARTURES = "FETCH_DEPARTURES";
export const FETCH_RETURNS = "FETCH_RETURNS";
export const CREATE_FLIGHT = "CREATE_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";

export const ADD_FLIGHT = "ADD_FLIGHT";
export const SET_PASSENGERS = "SET_PASSENGERS";
export const FETCH_BOOKINGS = "FETCH_BOOKINGS";
export const CHECKOUT = "CHECKOUT";

export const SET_USER = "SET_USER";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_AIRLINE_FLIGHTS = "FETCH_AIRLINE_FLIGHTS";
